### ISSUE TITLE
Not working with Skript 2.15.0

### ISSUE THREAD

**Issue by aayankhaan** [APickledWalrus/skript-placeholders#82]
### Project Version

Purpur 1.21.11

Skript-Placeholders 1.7.0

Skript 2.15.0

### Bug Description

Plugin not working on Skript 2.15.0 

### Expected Behavior

Old api of skript 

### Steps to Reproduce

Just install plugin

### Errors or Screenshots

[02:07:09 ERROR]: Error occurred while enabling skript-placeholders v1.7.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'void ch.njol.skript.registrations.EventValues.registerEventValue(java.lang.Class, java.lang.Class, ch.njol.skript.util.Getter, int)'
        at skript-placeholders-1.7.0.jar//io.github.apickledwalrus.skriptplaceholders.skript.elements.StructCustomPlaceholder.<clinit>(StructCustomPlaceholder.java:60) ~[?:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:536) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:515) ~[?:?]
        at Skript-2.15.0.jar//org.skriptlang.skript.util.ClassLoader.loadClasses(ClassLoader.java:191) ~[?:?]
        at Skript-2.15.0.jar//org.skriptlang.skript.util.ClassLoader.loadClasses(ClassLoader.java:113) ~[?:?]
        at Skript-2.15.0.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:214) ~[?:?]
        at Skript-2.15.0.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:76) ~[?:?]
        at skript-placeholders-1.7.0.jar//io.github.apickledwalrus.skriptplaceholders.SkriptPlaceholders.onEnable(SkriptPlaceholders.java:48) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.21.11-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:207) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.11-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:610) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:640) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:408) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:392) ~[purpur-1.21.11.jar:1.21.11-2568-f57bd86]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:07:09 INFO]: [skript-placeholders] Disabling skript-placeholders v1.7.0
