### ISSUE TITLE
Update to 1.21 pls?

### ISSUE THREAD

**Issue by abcdxyz6969** [APickledWalrus/skript-placeholders#71]
### Suggestion

Title

### Why?

Title

### Alternatives Considered

Title

**Comment by APickledWalrus** [comment]
The addon should work on 1.21. Are you having issues?

**Comment by TheFox580** [comment]
For some reason, whenever I reload a skript with the plugin, it won't reload and give me this error

```
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! An unexpected error occurred with Skript. This issue is likely not your fault.
[21:48:18] [Server thread/ERROR]: #!#! You are using some plugins that alter how Skript works (addons).
[21:48:18] [Server thread/ERROR]: #!#! Full list of addons:
[21:48:18] [Server thread/ERROR]: #!#! skript-placeholders v1.5.2 (https://github.com/APickledWalrus/skript-placeholders)
[21:48:18] [Server thread/ERROR]: #!#! We could not identify related addons, it might also be a Skript issue.
[21:48:18] [Server thread/ERROR]: #!#! Try temporarily removing the listed plugins one by one to identify the cause.
[21:48:18] [Server thread/ERROR]: #!#! If removing a plugin resolves the issue, please report the problem to the plugin developer.
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! Stack trace:
[21:48:18] [Server thread/ERROR]: #!#! Caused by: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'boolean ch.njol.skript.ScriptLoader.isCurrentEvent(java.lang.Class)'
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:687)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:486)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.Skript$1.run(Skript.java:701)
[21:48:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:48:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:48:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[21:48:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[21:48:18] [Server thread/ERROR]: #!#! Caused by: java.lang.NoSuchMethodError: 'boolean ch.njol.skript.ScriptLoader.isCurrentEvent(java.lang.Class)'
[21:48:18] [Server thread/ERROR]: #!#!     at skript-placeholders-1.5.2.jar//io.github.apickledwalrus.skriptplaceholders.skript.elements.expressions.ExprPlaceholder.init(ExprPlaceholder.java:49)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:241)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:152)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:309)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:520)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:755)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:144)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:36)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:47)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:36)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:47)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:45)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:29)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:45)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1295)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:196)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:152)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.Condition.parse(Condition.java:117)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.sections.SecConditional.init(SecConditional.java:193)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.Section.init(Section.java:51)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:241)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:152)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.Section.lambda$parse$0(Section.java:164)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.Section$SectionContext.modify(Section.java:200)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.Section.parse(Section.java:163)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:991)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.lang.SkriptEvent.load(SkriptEvent.java:129)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.structures.StructEvent.load(StructEvent.java:67)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$9(ScriptLoader.java:543)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1755)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1743)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$14(ScriptLoader.java:534)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:486)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428)
[21:48:18] [Server thread/ERROR]: #!#!     at Skript-2.10.2.jar//ch.njol.skript.Skript$1.run(Skript.java:701)
[21:48:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:48:18] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:48:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225)
[21:48:18] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[21:48:18] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1583)
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! Skript: 2.10.2 (latest)
[21:48:18] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[21:48:18] [Server thread/ERROR]: #!#!     Date: 13:26:22.247586600
[21:48:18] [Server thread/ERROR]: #!#! Bukkit: 1.21.1-R0.1-SNAPSHOT
[21:48:18] [Server thread/ERROR]: #!#! Minecraft: 1.21.1
[21:48:18] [Server thread/ERROR]: #!#! Java: 21.0.5 (Java HotSpot(TM) 64-Bit Server VM 21.0.5+9-LTS-239)
[21:48:18] [Server thread/ERROR]: #!#! OS: Linux aarch64 5.4.17-2136.336.5.1.el8uek.aarch64
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! Server platform: Paper
[21:48:18] [Server thread/ERROR]: #!#! 
[21:48:18] [Server thread/ERROR]: #!#! Current node: null
[21:48:18] [Server thread/ERROR]: #!#! Current item: null
[21:48:18] [Server thread/ERROR]: #!#! Thread: Server thread
[21:48:18] [Server thread/ERROR]: #!#! Language: english
[21:48:18] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[21:48:18] [Server thread/ERROR]: #!#! End of Error.
[21:48:18] [Server thread/ERROR]: #!#! 
```

(Although this error shows in 1.21.1, it also has the same issue in 1.21.4)

**Comment by APickledWalrus** [comment]
You're using an outdated version. Try updating to 1.7.0 https://github.com/APickledWalrus/skript-placeholders/releases/tag/1.7.0
